name: common_github_search
description: Shared Code between AngularDart and Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  bloc:
    path: ../../../packages/bloc
  equatable: ^1.2.5
  http: ^0.12.0
  rxdart: ^0.24.0
