name: todos_app_core

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  intl: ^0.15.4
  flutter:
    sdk: flutter
  path_provider: ^0.4.1

dev_dependencies:
  test: ^1.3.0
  intl_translation:

flutter:
  uses-material-design: true