name: bloc
description: A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
version: 7.0.0-nullsafety.0
repository: https://github.com/felangel/bloc/tree/master/packages/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://github.com/felangel/bloc
documentation: https://bloclibrary.dev

# Can't be published until null safety is shipped without requiring a flag
publish_to: none
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  coverage: ^0.14.2
  pedantic: ^1.10.0-nullsafety.3
  rxdart:
    git:
      url: https://github.com/felangel/rxdart
      ref: nnbd
  test: ^1.16.0-nullsafety.12
