name: build

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/cubit.yaml"
      - "packages/cubit/**"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/cubit
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.8.3
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: pub get
      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .
      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings .
